/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.Controlador;
import static java.awt.Frame.NORMAL;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import modelos.ApartamentoResidencial;
import modelos.CasaResidencial;
import modelos.Comercial;

/**
 *
 * @author Martines
 */
public class IUCadastroImovel extends javax.swing.JFrame {

    /**
     * Creates new form IUCadastroImovel
     */
    public IUCadastroImovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCadastroCliente = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Salário = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoImovel = new javax.swing.JFormattedTextField();
        txtEndereco = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDadaConstru = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnCasaResid = new javax.swing.JRadioButton();
        jBtnApResi = new javax.swing.JRadioButton();
        jBtnComercial = new javax.swing.JRadioButton();
        btnCadImovel = new javax.swing.JButton();
        txtAreaConstru = new javax.swing.JTextField();
        txtAreaTotal = new javax.swing.JTextField();
        txtQtdVgaGarag = new javax.swing.JTextField();
        txtQtdBanheiro = new javax.swing.JTextField();
        txtIPTU = new javax.swing.JTextField();
        txtValorVenda = new javax.swing.JTextField();
        txtValorAluguel = new javax.swing.JTextField();
        txtAndar = new javax.swing.JTextField();
        txtValorCondo = new javax.swing.JTextField();
        txtImposto = new javax.swing.JTextField();
        txtQtdDormi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblCadastroCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblCadastroCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCadastroCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastroCliente.setText("Cadastro de Imóveis");
        lblCadastroCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setText("Andar");

        Salário.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Salário.setText("Taxa de Imposto Federal");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Endereço");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Área Total");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Área Construida");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Quantidade Banheiros");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Valor Aluguel");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Quantidade Dormitórios");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Data Contrução");

        try {
            txtDadaConstru.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDadaConstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDadaConstruActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Quantidade Vagas Garagem");

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel14.setText("Valor IPTU");

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setText("Valor Venda");

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel16.setText("Valor Condomínio");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tipos de Imóveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        buttonGroup1.add(jBtnCasaResid);
        jBtnCasaResid.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBtnCasaResid.setSelected(true);
        jBtnCasaResid.setText("Casa Residencial");
        jBtnCasaResid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCasaResidMouseClicked(evt);
            }
        });
        jBtnCasaResid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCasaResidActionPerformed(evt);
            }
        });

        buttonGroup1.add(jBtnApResi);
        jBtnApResi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBtnApResi.setText("Apartamento Residencial");
        jBtnApResi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnApResiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnApResiMouseExited(evt);
            }
        });
        jBtnApResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApResiActionPerformed(evt);
            }
        });

        buttonGroup1.add(jBtnComercial);
        jBtnComercial.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBtnComercial.setText("Comercial");
        jBtnComercial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnComercialMouseClicked(evt);
            }
        });
        jBtnComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComercialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnCasaResid)
                .addGap(96, 96, 96)
                .addComponent(jBtnApResi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBtnCasaResid)
                    .addComponent(jBtnApResi)
                    .addComponent(jBtnComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        btnCadImovel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnCadImovel.setText("Cadastrar");
        btnCadImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadImovelActionPerformed(evt);
            }
        });

        txtQtdBanheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdBanheiroActionPerformed(evt);
            }
        });

        txtAndar.setEnabled(false);

        txtValorCondo.setEnabled(false);

        txtImposto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorCondo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Salário)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAreaTotal)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAreaConstru, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQtdDormi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQtdVgaGarag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDadaConstru, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btnCadImovel)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDadaConstru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtAreaConstru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdDormi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(txtQtdVgaGarag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6)
                    .addComponent(txtIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(Salário)
                    .addComponent(txtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCadImovel)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtDadaConstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDadaConstruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDadaConstruActionPerformed

    private void jBtnCasaResidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCasaResidMouseClicked

        txtAndar.setEnabled(false);
        txtValorCondo.setEnabled(false);
        txtImposto.setEnabled(false);
    }//GEN-LAST:event_jBtnCasaResidMouseClicked

    private void jBtnCasaResidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCasaResidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCasaResidActionPerformed

    private void jBtnApResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApResiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnApResiActionPerformed

    private void jBtnComercialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnComercialMouseClicked
         
            txtAndar.setEnabled(false);
            txtValorCondo.setEnabled(false);
            txtImposto.setEnabled(true); 
    }//GEN-LAST:event_jBtnComercialMouseClicked

    private void jBtnComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnComercialActionPerformed

    private void jBtnApResiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnApResiMouseClicked

        txtAndar.setEnabled(true);
        txtValorCondo.setEnabled(true);
        txtImposto.setEnabled(false); 

    }//GEN-LAST:event_jBtnApResiMouseClicked

    private void jBtnApResiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnApResiMouseExited
      
    }//GEN-LAST:event_jBtnApResiMouseExited

    private void btnCadImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadImovelActionPerformed
        
        
        if((txtValorVenda.getText().length() == 0 )||(txtValorAluguel.getText().length() == 0)||
            (txtQtdVgaGarag.getText().length() == 0)||(txtQtdDormi.getText().length() == 0)||
            (txtQtdBanheiro.getText().length() == 0)||(txtEndereco.getText().length() == 0)||
            (txtIPTU.getText().length() == 0 )||(txtDadaConstru.getText().length() == 0)||
            (txtAreaTotal.getText().length() == 0)||(txtAreaConstru.getText().length() == 0)||
            (txtCodigoImovel.getText().length() == 0)){

            JOptionPane.showMessageDialog(null,"Preencha todos os campos!" , 
            "Erro no Cadastro!", NORMAL);
        }else{    
            if(jBtnCasaResid.isSelected()){
                Float valorVenda = Float.parseFloat(txtValorVenda.getText());
                Float valorAluguel = Float.parseFloat(txtValorAluguel.getText());
                int qtdVagaGarag = Integer.parseInt(txtQtdVgaGarag.getText());
                int qtdDormi = Integer.parseInt(txtQtdDormi.getText());
                int qtdBanheiro = Integer.parseInt(txtQtdBanheiro.getText());
                String endereco = txtEndereco.getText();
                Float valorIPTU = Float.parseFloat(txtIPTU.getText());
                String dataConstru = txtDadaConstru.getText();
                LocalDate dateConstru = LocalDate.parse(dataConstru,DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                Float areaTotal = Float.parseFloat(txtAreaTotal.getText());
                Float areaConstru = Float.parseFloat(txtAreaConstru.getText());
                int codImovel = Integer.parseInt(txtCodigoImovel.getText()); 

                Controlador control = new Controlador();
                CasaResidencial casa = new CasaResidencial(codImovel, endereco, dateConstru, areaTotal , areaConstru, qtdDormi, 
                                           qtdBanheiro, qtdVagaGarag, valorIPTU, valorVenda, valorAluguel,  
                                           true, true);
                control.addImovel(casa);
               


                }else if(jBtnApResi.isSelected()){
                    
                    if((txtAndar.getText().length() == 0 )||(txtValorCondo.getText().length() == 0)){
                        JOptionPane.showMessageDialog(null,"Preencha todos os campos!" , 
                        "Erro no Cadastro!", NORMAL);
                        
                    }else{
                        Float valorVenda = Float.parseFloat(txtValorVenda.getText());
                        Float valorAluguel = Float.parseFloat(txtValorAluguel.getText());
                        int qtdVagaGarag = Integer.parseInt(txtQtdVgaGarag.getText());
                        int qtdDormi = Integer.parseInt(txtQtdDormi.getText());
                        int qtdBanheiro = Integer.parseInt(txtQtdBanheiro.getText());
                        String endereco = txtEndereco.getText();
                        Float valorIPTU = Float.parseFloat(txtIPTU.getText());
                        String dataConstru = txtDadaConstru.getText();
                        LocalDate dateConstru = LocalDate.parse(dataConstru,DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                        Float areaTotal = Float.parseFloat(txtAreaTotal.getText());
                        Float areaConstru = Float.parseFloat(txtAreaConstru.getText());
                        int codImovel = Integer.parseInt(txtCodigoImovel.getText()); 
                        int andar = Integer.parseInt(txtAndar.getText()); 
                        float valorCondo = Float.parseFloat(txtValorCondo.getText()); 

                        Controlador control = new Controlador();
                        ApartamentoResidencial apResid = new ApartamentoResidencial(andar, valorCondo, codImovel, endereco, dateConstru, areaTotal , areaConstru, qtdDormi, 
                                                                                    qtdBanheiro, qtdVagaGarag, valorIPTU, valorVenda, valorAluguel,  
                                                                                    true, true);

                        control.addImovel(apResid);
                    }

                }else{
                    
                    if((txtImposto.getText().length() == 0 )){
                       
                        JOptionPane.showMessageDialog(null,"Preencha todos os campos!" , 
                        "Erro no Cadastro!", NORMAL);
                        
                    }else{
                        Float valorVenda = Float.parseFloat(txtValorVenda.getText());
                        Float valorAluguel = Float.parseFloat(txtValorAluguel.getText());
                        int qtdVagaGarag = Integer.parseInt(txtQtdVgaGarag.getText());
                        int qtdDormi = Integer.parseInt(txtQtdDormi.getText());
                        int qtdBanheiro = Integer.parseInt(txtQtdBanheiro.getText());
                        String endereco = txtEndereco.getText();
                        Float valorIPTU = Float.parseFloat(txtIPTU.getText());
                        String dataConstru = txtDadaConstru.getText();
                        LocalDate dateConstru = LocalDate.parse(dataConstru,DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                        Float areaTotal = Float.parseFloat(txtAreaTotal.getText());
                        Float areaConstru = Float.parseFloat(txtAreaConstru.getText());
                        int codImovel = Integer.parseInt(txtCodigoImovel.getText()); 
                        float impostoFederal = Float.parseFloat(txtImposto.getText()); 

                        Controlador control = new Controlador();
                        Comercial comercial = new Comercial(impostoFederal, codImovel, endereco, dateConstru, areaTotal , areaConstru, qtdDormi, 
                                                                                    qtdBanheiro, qtdVagaGarag, valorIPTU, valorVenda, valorAluguel,  
                                                                                    true, true);

                        control.addImovel(comercial);
                        
                    }
                }


            }
    }//GEN-LAST:event_btnCadImovelActionPerformed

    private void txtQtdBanheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdBanheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdBanheiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUCadastroImovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salário;
    private javax.swing.JButton btnCadImovel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jBtnApResi;
    private javax.swing.JRadioButton jBtnCasaResid;
    private javax.swing.JRadioButton jBtnComercial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastroCliente;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtAreaConstru;
    private javax.swing.JTextField txtAreaTotal;
    private javax.swing.JFormattedTextField txtCodigoImovel;
    private javax.swing.JFormattedTextField txtDadaConstru;
    private javax.swing.JFormattedTextField txtEndereco;
    private javax.swing.JTextField txtIPTU;
    private javax.swing.JTextField txtImposto;
    private javax.swing.JTextField txtQtdBanheiro;
    private javax.swing.JTextField txtQtdDormi;
    private javax.swing.JTextField txtQtdVgaGarag;
    private javax.swing.JTextField txtValorAluguel;
    private javax.swing.JTextField txtValorCondo;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
