/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import controladores.Controlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Seguro;

/**
 *
 * @author Martines
 */
public class IUConsultaSeguro extends javax.swing.JDialog {
    private DefaultTableModel model; 
    private Controlador control; 
    private String codSeguros; 
    private String seguradoura; 
    private String desc; 
    private String tipoSeg;
    private String valor; 
    /**
     * Creates new form IUConsultaSeguro
     */
    public IUConsultaSeguro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        control = new Controlador();

        codSeguros = null; 
        String colunas[] = {"Código","Seguradoura","Tipo Seguro","Descrição","Valor"};
        model = (DefaultTableModel)tabelaSeguros.getModel();//new DefaultTableModel(colunas,0);
        
        ArrayList<Seguro> seguros = control.listaTodosSeguros();
        
           if(seguros != null){
            for(int i = 0; i < seguros.size(); i++){
                if (seguros.get(i) != null){
                    String line[] = new String[5];
                    line[0] = Integer.toString(seguros.get(i).getCodigoSeguro());
                    line[1] = seguros.get(i).getNomeSeguradora();
                    line[2] = seguros.get(i).getTipo();
                    line[3] = seguros.get(i).getDescricao();
                    line[4] = Float.toString(seguros.get(i).getValor());                  
                    model.addRow(line);
                }
             }
        }else{
            JOptionPane.showMessageDialog(this, "Não há nenhum seguro cadastrado!");
        }
        
           
    }

    public String getCodSeguro(){
               return this.codSeguros; 
           }
    
    public String getSeguradoura(){
        return this.seguradoura;
    }
    
    public String getDesSeg(){
        return this.desc; 
    }
    
    public String getTipoSeg(){
        return this.tipoSeg; 
    }
    
    public String getValor(){
        return this.valor; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaSeguros = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaSeguros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tabelaSeguros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Seguradoura", "Tipo Seguro", "Descrição", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tabelaSeguros);

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnSelecionar)
                        .addGap(132, 132, 132)
                        .addComponent(btnFechar)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar)
                    .addComponent(btnFechar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        codSeguros = null; 
        setVisible(false); 
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int line = tabelaSeguros.getSelectedRow(); 
        if(line >=0){
            codSeguros = (String) model.getValueAt(line,0);
            seguradoura = (String) model.getValueAt(line, 1);
            tipoSeg = (String) model.getValueAt(line, 2);
            desc = (String) model.getValueAt(line, 3); 
            valor = (String) model.getValueAt(line, 4);
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Seleciona um item!");
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUConsultaSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUConsultaSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUConsultaSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUConsultaSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUConsultaSeguro dialog = new IUConsultaSeguro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaSeguros;
    // End of variables declaration//GEN-END:variables
}
