/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Martines
 */
public class IUPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemCorretor = new javax.swing.JMenuItem();
        subMenuCadImovel = new javax.swing.JMenu();
        menuItemApResidencial = new javax.swing.JMenuItem();
        menuItemComercial = new javax.swing.JMenuItem();
        menuItemVenda = new javax.swing.JMenuItem();
        jMenuRelat = new javax.swing.JMenu();
        subMenuRelCli = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        subMenuRelCorre = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        subMenuRelVend = new javax.swing.JMenu();
        subMenuRelImovel = new javax.swing.JMenu();
        jMenuTodosImoveis = new javax.swing.JMenuItem();
        jMenuCasasResid = new javax.swing.JMenuItem();
        jMenuApResidencial = new javax.swing.JMenuItem();
        jMenuComerciais = new javax.swing.JMenuItem();
        jMenuImoveisDispAlu = new javax.swing.JMenuItem();
        jMenuImoveisDispVend = new javax.swing.JMenuItem();
        jMenuImoveisIndisp = new javax.swing.JMenuItem();
        jMenuImovAtrasoAlug = new javax.swing.JMenuItem();
        jMenuAlugCliEsp = new javax.swing.JMenuItem();
        jMenuVendaCliEsp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCadastros.setText("Cadastros ");

        menuItemCliente.setText("Cadastro Cliente");
        jMenuCadastros.add(menuItemCliente);

        menuItemCorretor.setText("Cadastro Corretor ");
        jMenuCadastros.add(menuItemCorretor);

        subMenuCadImovel.setText("Cadastro Imovel ");

        menuItemApResidencial.setText("Cadastro Apartamento Residencial");
        subMenuCadImovel.add(menuItemApResidencial);

        menuItemComercial.setText("Cadastro Comercial ");
        subMenuCadImovel.add(menuItemComercial);

        jMenuCadastros.add(subMenuCadImovel);

        menuItemVenda.setText("Cadastro Venda ");
        jMenuCadastros.add(menuItemVenda);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelat.setText("Relatórios");

        subMenuRelCli.setText("Relatório de Clientes ");

        jMenuItem1.setText("jMenuItem1");
        subMenuRelCli.add(jMenuItem1);

        jMenuRelat.add(subMenuRelCli);

        subMenuRelCorre.setText("Relatório de Corretores ");

        jMenuItem2.setText("jMenuItem2");
        subMenuRelCorre.add(jMenuItem2);

        jMenuRelat.add(subMenuRelCorre);

        subMenuRelVend.setText("Relatório de Aluguel e Vendas  ");
        jMenuRelat.add(subMenuRelVend);

        subMenuRelImovel.setText("Relatório de imóveis ");

        jMenuTodosImoveis.setText("Todos Imóveis");
        jMenuTodosImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTodosImoveisActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuTodosImoveis);

        jMenuCasasResid.setText("Casas Residenciais");
        subMenuRelImovel.add(jMenuCasasResid);

        jMenuApResidencial.setText("Apartamentos Residenciais");
        subMenuRelImovel.add(jMenuApResidencial);

        jMenuComerciais.setText("Comerciais");
        jMenuComerciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComerciaisActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuComerciais);

        jMenuImoveisDispAlu.setText("Imóveis Disponíveis (Aluguel)");
        subMenuRelImovel.add(jMenuImoveisDispAlu);

        jMenuImoveisDispVend.setText("Imóveis Disponíveis (Venda)");
        subMenuRelImovel.add(jMenuImoveisDispVend);

        jMenuImoveisIndisp.setText("Imóveis Indisponíveis");
        subMenuRelImovel.add(jMenuImoveisIndisp);

        jMenuImovAtrasoAlug.setText("Imóveis Aluguel Atrasado");
        subMenuRelImovel.add(jMenuImovAtrasoAlug);

        jMenuAlugCliEsp.setText("Imóveis Alugados Cliente Específico");
        jMenuAlugCliEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlugCliEspActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuAlugCliEsp);

        jMenuVendaCliEsp.setText("Imóveis Comprados Cliente Específico ");
        subMenuRelImovel.add(jMenuVendaCliEsp);

        jMenuRelat.add(subMenuRelImovel);

        jMenuBar1.add(jMenuRelat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuTodosImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTodosImoveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTodosImoveisActionPerformed

    private void jMenuComerciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComerciaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuComerciaisActionPerformed

    private void jMenuAlugCliEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlugCliEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlugCliEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuAlugCliEsp;
    private javax.swing.JMenuItem jMenuApResidencial;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuCasasResid;
    private javax.swing.JMenuItem jMenuComerciais;
    private javax.swing.JMenuItem jMenuImovAtrasoAlug;
    private javax.swing.JMenuItem jMenuImoveisDispAlu;
    private javax.swing.JMenuItem jMenuImoveisDispVend;
    private javax.swing.JMenuItem jMenuImoveisIndisp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuRelat;
    private javax.swing.JMenuItem jMenuTodosImoveis;
    private javax.swing.JMenuItem jMenuVendaCliEsp;
    private javax.swing.JMenuItem menuItemApResidencial;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemComercial;
    private javax.swing.JMenuItem menuItemCorretor;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenu subMenuCadImovel;
    private javax.swing.JMenu subMenuRelCli;
    private javax.swing.JMenu subMenuRelCorre;
    private javax.swing.JMenu subMenuRelImovel;
    private javax.swing.JMenu subMenuRelVend;
    // End of variables declaration//GEN-END:variables
}
