/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.Controlador;

/**
 *
 * @author Martines
 */
public class IUPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemCorretor = new javax.swing.JMenuItem();
        menuItemVenda = new javax.swing.JMenuItem();
        menuItemImovel = new javax.swing.JMenuItem();
        menuItemAluguel = new javax.swing.JMenuItem();
        menuItemSeguro = new javax.swing.JMenuItem();
        jMenuRelat = new javax.swing.JMenu();
        subMenuRelCli = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuCompraCliEsp = new javax.swing.JMenuItem();
        jMenuCliAluguelAtraso = new javax.swing.JMenuItem();
        subMenuRelCorre = new javax.swing.JMenu();
        jMenuCorretores = new javax.swing.JMenuItem();
        jMenuFuncDoMês = new javax.swing.JMenuItem();
        subMenuRelVend = new javax.swing.JMenu();
        jMenuIAlugueis = new javax.swing.JMenuItem();
        jMenuAlugFinalizados = new javax.swing.JMenuItem();
        jMenuAlugNaoFinalizados = new javax.swing.JMenuItem();
        jMenuCasasContrVigente = new javax.swing.JMenuItem();
        jMenuApContrVigente = new javax.swing.JMenuItem();
        jMenuComerciaisContrVigente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuVendas = new javax.swing.JMenuItem();
        jMenuLucrosTotais = new javax.swing.JMenuItem();
        jMenuMesesEspeci = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuSeguros = new javax.swing.JMenuItem();
        subMenuRelImovel = new javax.swing.JMenu();
        jMenuTodosImoveis = new javax.swing.JMenuItem();
        jMenuCasasResid = new javax.swing.JMenuItem();
        jMenuApResidencial = new javax.swing.JMenuItem();
        jMenuComerciais = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuImoveisDispAlu = new javax.swing.JMenuItem();
        jMenuImoveisDispVend = new javax.swing.JMenuItem();
        jMenuImoveisIndisp = new javax.swing.JMenuItem();
        jMenuImovAtrasoAlug = new javax.swing.JMenuItem();
        jMenuAlugCliEsp = new javax.swing.JMenuItem();
        jMenuVendaCliEsp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jMenuCadastros.setText("Cadastros ");
        jMenuCadastros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosActionPerformed(evt);
            }
        });

        menuItemCliente.setText("Cadastro Cliente");
        menuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemCliente);

        menuItemCorretor.setText("Cadastro Corretor ");
        menuItemCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCorretorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemCorretor);

        menuItemVenda.setText("Cadastro Venda ");
        menuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemVenda);

        menuItemImovel.setText("Cadastro Imóvel");
        menuItemImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemImovelActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemImovel);

        menuItemAluguel.setText("Cadastro Locação");
        menuItemAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAluguelActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemAluguel);

        menuItemSeguro.setText("Cadastro Seguro");
        menuItemSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeguroActionPerformed(evt);
            }
        });
        jMenuCadastros.add(menuItemSeguro);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelat.setText("Relatórios");
        jMenuRelat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        subMenuRelCli.setText("Relatório de Clientes ");

        jMenuClientes.setText("Todos Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        subMenuRelCli.add(jMenuClientes);

        jMenuCompraCliEsp.setText("Histórico de Compra Cliente Específico");
        jMenuCompraCliEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompraCliEspActionPerformed(evt);
            }
        });
        subMenuRelCli.add(jMenuCompraCliEsp);

        jMenuCliAluguelAtraso.setText("Clientes com Aluguel em Atraso");
        jMenuCliAluguelAtraso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCliAluguelAtrasoActionPerformed(evt);
            }
        });
        subMenuRelCli.add(jMenuCliAluguelAtraso);

        jMenuRelat.add(subMenuRelCli);

        subMenuRelCorre.setText("Relatório de Corretores ");

        jMenuCorretores.setText("Todos Corretores ");
        jMenuCorretores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCorretoresActionPerformed(evt);
            }
        });
        subMenuRelCorre.add(jMenuCorretores);

        jMenuFuncDoMês.setText("Funcionários do Mês");
        subMenuRelCorre.add(jMenuFuncDoMês);

        jMenuRelat.add(subMenuRelCorre);

        subMenuRelVend.setText("Relatório de Aluguel e Vendas  ");

        jMenuIAlugueis.setText("Todos Alugueis");
        jMenuIAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIAlugueisActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuIAlugueis);

        jMenuAlugFinalizados.setText("Alugueis Finalizados");
        jMenuAlugFinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlugFinalizadosActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuAlugFinalizados);

        jMenuAlugNaoFinalizados.setText("Alugueis Não Finalizados ");
        jMenuAlugNaoFinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlugNaoFinalizadosActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuAlugNaoFinalizados);

        jMenuCasasContrVigente.setText("Casas Residenciais Alugadas (Contrado Vigente)");
        jMenuCasasContrVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCasasContrVigenteActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuCasasContrVigente);

        jMenuApContrVigente.setText("Apartamentos Residenciais Alugados (Contrato Vigente)");
        jMenuApContrVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuApContrVigenteActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuApContrVigente);

        jMenuComerciaisContrVigente.setText("Estabelecimentos Comerciais Alugados (Contrato Vigente)");
        jMenuComerciaisContrVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComerciaisContrVigenteActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuComerciaisContrVigente);
        subMenuRelVend.add(jSeparator1);

        jMenuVendas.setText("Todas as Vendas");
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuVendas);

        jMenuLucrosTotais.setText("Lucros Totais das Vendas ");
        jMenuLucrosTotais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLucrosTotaisActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuLucrosTotais);

        jMenuMesesEspeci.setText("Vendas em Meses Específicos");
        jMenuMesesEspeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMesesEspeciActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuMesesEspeci);
        subMenuRelVend.add(jSeparator2);

        jMenuSeguros.setText("Seguros Cadastrados");
        jMenuSeguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSegurosActionPerformed(evt);
            }
        });
        subMenuRelVend.add(jMenuSeguros);

        jMenuRelat.add(subMenuRelVend);

        subMenuRelImovel.setText("Relatório de imóveis ");

        jMenuTodosImoveis.setText("Todos Imóveis");
        jMenuTodosImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTodosImoveisActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuTodosImoveis);

        jMenuCasasResid.setText("Casas Residenciais");
        jMenuCasasResid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCasasResidActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuCasasResid);

        jMenuApResidencial.setText("Apartamentos Residenciais");
        jMenuApResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuApResidencialActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuApResidencial);

        jMenuComerciais.setText("Estabelecimentos Comerciais");
        jMenuComerciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComerciaisActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuComerciais);
        subMenuRelImovel.add(jSeparator3);

        jMenuImoveisDispAlu.setText("Imóveis Disponíveis (Aluguel)");
        jMenuImoveisDispAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImoveisDispAluActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuImoveisDispAlu);

        jMenuImoveisDispVend.setText("Imóveis Disponíveis (Venda)");
        jMenuImoveisDispVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImoveisDispVendActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuImoveisDispVend);

        jMenuImoveisIndisp.setText("Imóveis Indisponíveis");
        jMenuImoveisIndisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImoveisIndispActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuImoveisIndisp);

        jMenuImovAtrasoAlug.setText("Imóveis Aluguel Atrasado");
        subMenuRelImovel.add(jMenuImovAtrasoAlug);

        jMenuAlugCliEsp.setText("Imóveis Alugados Cliente Específico");
        jMenuAlugCliEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlugCliEspActionPerformed(evt);
            }
        });
        subMenuRelImovel.add(jMenuAlugCliEsp);

        jMenuVendaCliEsp.setText("Imóveis Comprados Cliente Específico ");
        subMenuRelImovel.add(jMenuVendaCliEsp);

        jMenuRelat.add(subMenuRelImovel);

        jMenuBar1.add(jMenuRelat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuTodosImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTodosImoveisActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosImoveis =  new IURelatorioTodosGeral(null, false);
        relatorioTodosImoveis.exibir("Relatório Todos os Imóveis Cadastrados", "Todos os Todos os Imóveis Cadastrados" , control.listaTodosOsImoveis().toString());
    }//GEN-LAST:event_jMenuTodosImoveisActionPerformed

    private void jMenuComerciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComerciaisActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosComerciais =  new IURelatorioTodosGeral(null, false);
        relatorioTodosComerciais.exibir("Relatório Todos os Imóveis Comerciais Cadastrados", "Todos os Todos os Imóveis Comerciais Cadastrados" , control.listaTodosOsComerciais().toString());
    }//GEN-LAST:event_jMenuComerciaisActionPerformed

    private void jMenuAlugCliEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlugCliEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlugCliEspActionPerformed

    private void jMenuCasasContrVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCasasContrVigenteActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral casasContVigente = new IURelatorioTodosGeral(null, false);
        casasContVigente.exibir("Relatório Casas Residenciais Alugadas Com Cotrato Vigente", "Relatório Casas Residenciais Alugadas Com Cotrato Vigente", control.listaCasasResidenciaisContratoVigente().toString());
    }//GEN-LAST:event_jMenuCasasContrVigenteActionPerformed

    private void jMenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosActionPerformed
        
    }//GEN-LAST:event_jMenuCadastrosActionPerformed

    private void menuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClienteActionPerformed
        new IUCadastroCliente().setVisible(true);
    }//GEN-LAST:event_menuItemClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void menuItemCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCorretorActionPerformed
        new IUCadastroCorretor().setVisible(true);
    }//GEN-LAST:event_menuItemCorretorActionPerformed


    private void menuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaActionPerformed
        new IUCadastroVenda().setVisible(true);
    }//GEN-LAST:event_menuItemVendaActionPerformed

    private void menuItemSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeguroActionPerformed
        new IUCadastroSeguro().setVisible(true);
    }//GEN-LAST:event_menuItemSeguroActionPerformed

    private void menuItemImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemImovelActionPerformed
        new IUCadastroImovel().setVisible(true); 
    }//GEN-LAST:event_menuItemImovelActionPerformed


    private void menuItemAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAluguelActionPerformed
        new IUCadastroAluguell().setVisible(true);
    }//GEN-LAST:event_menuItemAluguelActionPerformed

    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosClientes =  new IURelatorioTodosGeral(null, false);
        relatorioTodosClientes.exibir("Relatório Todos os Clientes Cadastrados", "Todos os Clientes Cadastrados" , control.getTodosClientes().toString());
        
        
    }//GEN-LAST:event_jMenuClientesActionPerformed

    private void jMenuCorretoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCorretoresActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosCorretores =  new IURelatorioTodosGeral(null, false);
        relatorioTodosCorretores.exibir("Relatório Todos os Corretores Cadastrados", "Todos os Corretores Cadastrados" , control.getTodosCOrretores().toString());
    }//GEN-LAST:event_jMenuCorretoresActionPerformed

    private void jMenuIAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIAlugueisActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosAlugueis =  new IURelatorioTodosGeral(null, false);
        relatorioTodosAlugueis.exibir("Relatório Todos os Alugueis Cadastrados", "Todos os Alugueis" , control.listaTodosOsAlugueis().toString());
    }//GEN-LAST:event_jMenuIAlugueisActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosVendas =  new IURelatorioTodosGeral(null, false);
        relatorioTodosVendas.exibir("Relatório Todos os Vendas Cadastrados", "Todas as Vendas" , control.listaTodasVendas().toString());
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSegurosActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosSeguros =  new IURelatorioTodosGeral(null, false);
        relatorioTodosSeguros.exibir("Relatório Todos os Seguros Cadastrados", "Todas os Seguros Cadastrados" , control.listaTodosSeguros().toString());
    }//GEN-LAST:event_jMenuSegurosActionPerformed

    private void jMenuCasasResidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCasasResidActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosCasa =  new IURelatorioTodosGeral(null, false);
        relatorioTodosCasa.exibir("Relatório Todas as Casas Residenciais Cadastrados", "Todas as Casas Residenciais Cadastrados" , control.listaTodasAsCasasResidenciais().toString());
    }//GEN-LAST:event_jMenuCasasResidActionPerformed

    private void jMenuApResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuApResidencialActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioTodosApResi =  new IURelatorioTodosGeral(null, false);
        relatorioTodosApResi.exibir("Relatório Todos os Apartamentos Residenciais Cadastrados", "Todos os Apartamentos Residenciais Cadastrados" , control.listaTodosOsApartamentosResidenciais().toString());
    }//GEN-LAST:event_jMenuApResidencialActionPerformed

    private void jMenuCliAluguelAtrasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCliAluguelAtrasoActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioCliAluguelAtrasado =  new IURelatorioTodosGeral(null, false);
        relatorioCliAluguelAtrasado.exibir("Relatório Todos os Apartamentos Residenciais Cadastrados", "Todos os Clientes com Alugueis em atraso" , control.listaClientesComAlugueisAtrasados().toString());
        
    }//GEN-LAST:event_jMenuCliAluguelAtrasoActionPerformed

    private void jMenuImoveisDispVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImoveisDispVendActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioImovDisp =  new IURelatorioTodosGeral(null, false);
        relatorioImovDisp.exibir("Relatório Todos imóveis disponíveis para Compra", "Todos os imóveis disponíveis para Compra" , control.listaImoveisDisponiveisCompra().toString());
    }//GEN-LAST:event_jMenuImoveisDispVendActionPerformed

    private void jMenuImoveisIndispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImoveisIndispActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioImovIndisp =  new IURelatorioTodosGeral(null, false);
        relatorioImovIndisp.exibir("Relatório Todos imóveis Indisponíveis para Compra/Aluguel", "Todos os imóveis Indisponíveis para Compra/Locação" , control.listaImoveisIndisponiveis().toString());
    }//GEN-LAST:event_jMenuImoveisIndispActionPerformed

    private void jMenuCompraCliEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompraCliEspActionPerformed
        IURelatorioBuscaImoveisCompradosClienteEspecifico relCompraCliEspec = new IURelatorioBuscaImoveisCompradosClienteEspecifico(null, false);
        relCompraCliEspec.setVisible(true);
    }//GEN-LAST:event_jMenuCompraCliEspActionPerformed

    private void jMenuLucrosTotaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLucrosTotaisActionPerformed
        IURelatorioTodasAsVendasLucroTotal todasVendasLucroTotal = new IURelatorioTodasAsVendasLucroTotal(null, false);
        todasVendasLucroTotal.setVisible(true);
    }//GEN-LAST:event_jMenuLucrosTotaisActionPerformed

    private void jMenuMesesEspeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMesesEspeciActionPerformed
        IURelatorioVendasMesLucroMes vendasMesLucroMes = new IURelatorioVendasMesLucroMes(null, false);
        vendasMesLucroMes.setVisible(true);
    }//GEN-LAST:event_jMenuMesesEspeciActionPerformed

    private void jMenuApContrVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuApContrVigenteActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral apContVigente = new IURelatorioTodosGeral(null, false);
        apContVigente.exibir("Relatório Apartamento Residenciais Alugadas Com Cotrato Vigente", "Relatório Apartamentos Residenciais Alugadas Com Cotrato Vigente", control.listaApartamentosResidenciaisContratoVigente().toString());
    }//GEN-LAST:event_jMenuApContrVigenteActionPerformed

    private void jMenuComerciaisContrVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComerciaisContrVigenteActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral comContVigente = new IURelatorioTodosGeral(null, false);
        comContVigente.exibir("Relatório Estabelecimentos Comerciais Alugadas Com Cotrato Vigente", "Relatório Estabelecimentos Comerciais Alugadas Com Cotrato Vigente", control.listaComerciaisContratoVigente().toString());
    }//GEN-LAST:event_jMenuComerciaisContrVigenteActionPerformed

    private void jMenuAlugNaoFinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlugNaoFinalizadosActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral alugNaoFinalizados = new IURelatorioTodosGeral(null, false);
        alugNaoFinalizados.exibir("Relatório de Alugueis ainda não Finalizados", "Relatório de Alugueis ainda não Finalizados", control.listaAlugueisNaoFinalizados().toString());
    }//GEN-LAST:event_jMenuAlugNaoFinalizadosActionPerformed

    private void jMenuAlugFinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlugFinalizadosActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral alugFinalizados = new IURelatorioTodosGeral(null, false);
        alugFinalizados.exibir("Relatório de Alugueis Finalizados", "Relatório de Alugueis Finalizados", control.listaAlugueisFinalizados().toString());
    }//GEN-LAST:event_jMenuAlugFinalizadosActionPerformed

    private void jMenuImoveisDispAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImoveisDispAluActionPerformed
        Controlador control = new Controlador();
        IURelatorioTodosGeral relatorioImovDispAluguel =  new IURelatorioTodosGeral(null, false);
        relatorioImovDispAluguel.exibir("Relatório Todos imóveis disponíveis para Aluguel", "Todos os imóveis disponíveis para Aluguel" , control.listaImoveisDisponiveisLocacao().toString());
    }//GEN-LAST:event_jMenuImoveisDispAluActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuAlugCliEsp;
    private javax.swing.JMenuItem jMenuAlugFinalizados;
    private javax.swing.JMenuItem jMenuAlugNaoFinalizados;
    private javax.swing.JMenuItem jMenuApContrVigente;
    private javax.swing.JMenuItem jMenuApResidencial;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuCasasContrVigente;
    private javax.swing.JMenuItem jMenuCasasResid;
    private javax.swing.JMenuItem jMenuCliAluguelAtraso;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuComerciais;
    private javax.swing.JMenuItem jMenuComerciaisContrVigente;
    private javax.swing.JMenuItem jMenuCompraCliEsp;
    private javax.swing.JMenuItem jMenuCorretores;
    private javax.swing.JMenuItem jMenuFuncDoMês;
    private javax.swing.JMenuItem jMenuIAlugueis;
    private javax.swing.JMenuItem jMenuImovAtrasoAlug;
    private javax.swing.JMenuItem jMenuImoveisDispAlu;
    private javax.swing.JMenuItem jMenuImoveisDispVend;
    private javax.swing.JMenuItem jMenuImoveisIndisp;
    private javax.swing.JMenuItem jMenuLucrosTotais;
    private javax.swing.JMenuItem jMenuMesesEspeci;
    private javax.swing.JMenu jMenuRelat;
    private javax.swing.JMenuItem jMenuSeguros;
    private javax.swing.JMenuItem jMenuTodosImoveis;
    private javax.swing.JMenuItem jMenuVendaCliEsp;
    private javax.swing.JMenuItem jMenuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem menuItemAluguel;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemCorretor;
    private javax.swing.JMenuItem menuItemImovel;
    private javax.swing.JMenuItem menuItemSeguro;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenu subMenuRelCli;
    private javax.swing.JMenu subMenuRelCorre;
    private javax.swing.JMenu subMenuRelImovel;
    private javax.swing.JMenu subMenuRelVend;
    // End of variables declaration//GEN-END:variables
}
