/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package interfaces;

import controladores.Controlador;
import modelos.Cliente;

/**
 *
 * @author Lucas
 */
public class IURelatorioBuscaImoveisCompradosClienteEspecifico extends java.awt.Dialog {

    /**
     * Creates new form IURelatorioBuscaEspecificaGeral
     */
    public IURelatorioBuscaImoveisCompradosClienteEspecifico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRelatorio = new javax.swing.JLabel();
        lblTipoBusca = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        btnConsultaCli = new javax.swing.JButton();
        btnExibeRelatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHistorico = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        lblTituloRelatorio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTituloRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRelatorio.setText("Histórico de Compras de um Cliente Específico");

        lblTipoBusca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTipoBusca.setText("Código Cliente");

        btnConsultaCli.setText("Consultar Cliente");
        btnConsultaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCliActionPerformed(evt);
            }
        });

        btnExibeRelatorio.setText("Exibir Relatório");
        btnExibeRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibeRelatorioActionPerformed(evt);
            }
        });

        txtAreaHistorico.setColumns(20);
        txtAreaHistorico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtAreaHistorico.setRows(5);
        jScrollPane1.setViewportView(txtAreaHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTipoBusca)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultaCli)
                        .addGap(18, 18, 18)
                        .addComponent(btnExibeRelatorio)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTituloRelatorio)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoBusca)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaCli)
                    .addComponent(btnExibeRelatorio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnConsultaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCliActionPerformed
        IUConsultaClientes consulClientes = new IUConsultaClientes(null, true);
        consulClientes.setVisible(true);
        String codCli = consulClientes.getCodCliente();
        txtCodCliente.setText(codCli);
    }//GEN-LAST:event_btnConsultaCliActionPerformed

    private void btnExibeRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibeRelatorioActionPerformed
        Controlador control = new Controlador();
        int codCli = Integer.parseInt(txtCodCliente.getText());
        
        txtAreaHistorico.setText(control.listaHistoricoComprasClienteEspecifico(codCli).toString());
        
        
    }//GEN-LAST:event_btnExibeRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IURelatorioBuscaImoveisCompradosClienteEspecifico dialog = new IURelatorioBuscaImoveisCompradosClienteEspecifico(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaCli;
    private javax.swing.JButton btnExibeRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoBusca;
    private javax.swing.JLabel lblTituloRelatorio;
    private javax.swing.JTextArea txtAreaHistorico;
    private javax.swing.JTextField txtCodCliente;
    // End of variables declaration//GEN-END:variables
}
